name: Build GMod-SDK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1

    - name: Download DX9 SDK from GitHub
      run: |
        Invoke-WebRequest -Uri "https://github.com/AliveTeam/DX9_SDK_Aug09/archive/refs/heads/master.zip" -OutFile dx9.zip
        Expand-Archive dx9.zip -DestinationPath C:\dx9
        New-Item -ItemType Directory -Path "C:\dx9\Include" -Force
        New-Item -ItemType Directory -Path "C:\dx9\Lib\x64" -Force
        Copy-Item -Path "C:\dx9\DX9_SDK_Aug09-master\Include\*" -Destination "C:\dx9\Include" -Recurse -Force
        Copy-Item -Path "C:\dx9\DX9_SDK_Aug09-master\Lib\x64\*" -Destination "C:\dx9\Lib\x64" -Recurse -Force

    - name: Build solution
      run: |
        $dxInclude = "C:\dx9\Include"
        $dxLib = "C:\dx9\Lib\x64"
        $windowsInclude = "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um"
        $windowsLib = "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64"
    
        msbuild GMod-SDK.sln /p:Configuration=Release /p:Platform=x64 /p:IncludePath="`"$dxInclude;$windowsInclude`"" /p:LibraryPath="`"$dxLib;$windowsLib`""
      shell: pwsh

    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: GMod-SDK-Release
        path: "**/Release/*.dll"
