name: Build GMod-SDK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1

    - name: Download DX9 SDK from GitHub
      run: |
        Invoke-WebRequest -Uri "https://github.com/AliveTeam/DX9_SDK_Aug09/archive/refs/heads/master.zip" -OutFile dx9.zip
        Expand-Archive dx9.zip -DestinationPath C:\dx9
        New-Item -ItemType Directory -Path "C:\dx9\Include" -Force
        New-Item -ItemType Directory -Path "C:\dx9\Lib\x64" -Force
        Copy-Item -Path "C:\dx9\DX9_SDK_Aug09-master\Include\*" -Destination "C:\dx9\Include" -Recurse -Force
        Copy-Item -Path "C:\dx9\DX9_SDK_Aug09-master\Lib\x64\*" -Destination "C:\dx9\Lib\x64" -Recurse -Force

    - name: Verify DX9 files
      run: |
        dir "C:\dx9\Include\d3dx9.h"
        dir "C:\dx9\Lib\x64\d3dx9.lib"
      shell: powershell
                
    - name: Build solution
      shell: cmd
      run: |
        set DXINC=C:\dx9\Include
        set DXLIB=C:\dx9\Lib\x64
    
        cd GMod-SDK\GMod-SDK
    
        msbuild GMod-SDK.sln /p:Configuration=Release /p:Platform=x64 /p:AdditionalIncludeDirectories=%DXINC% /p:AdditionalLibraryDirectories=%DXLIB%

    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: GMod-SDK-Release
        path: "**/Release/*.dll"
